In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat  

In [2]:
train= loadmat("train.mat") # taking the data input using loadmt fn to read it
print(train)
print(train.items())
val = loadmat("val.mat")
print(val)
test=loadmat("test.mat")
print(test)
print(train.__len__())
print(type(train))
print(type(val))
print(type(test))

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Thu Sep 29 13:21:50 2022', '__version__': '1.0', '__globals__': [], 'features': array([[ 0.,  0.,  4., ..., 11.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  4., 16., ...,  7.,  4.,  0.],
       ...,
       [ 0.,  0.,  3., ..., 14.,  7.,  0.],
       [ 0.,  0.,  2., ..., 13.,  7.,  0.],
       [ 0.,  0., 10., ..., 16., 16., 10.]]), 'label': array([[1., 4., 2., ..., 6., 6., 1.]])}
dict_items([('__header__', b'MATLAB 5.0 MAT-file Platform: posix, Created on: Thu Sep 29 13:21:50 2022'), ('__version__', '1.0'), ('__globals__', []), ('features', array([[ 0.,  0.,  4., ..., 11.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  4., 16., ...,  7.,  4.,  0.],
       ...,
       [ 0.,  0.,  3., ..., 14.,  7.,  0.],
       [ 0.,  0.,  2., ..., 13.,  7.,  0.],
       [ 0.,  0., 10., ..., 16., 16., 10.]])), ('label', array([[1., 4., 2., ..., 6., 6., 1.]]))])
{'__header__': b'MATLAB 5.0 MAT-

In [3]:
X_train= train['features'] # taking the colum called feature as a x_train 
Y_train= train['label']     # taking the last colum as label called y_train
print("train",X_train,Y_train)
print(X_train.shape)
Y_train=np.reshape(Y_train,(1077,1)) #reshape the y_train to allow the fitting process 
print(Y_train.shape)
X_val= val['features']  # taking the colum called feature as a x_val 
Y_val= val['label']    # taking the last colum as  label calledy_val
print("validation",X_val,Y_val)
print(X_val.shape)
Y_val=np.reshape(Y_val,(360,1)) #reshape the y_val to allow the fitting process 
print(Y_val.shape) 
X_test= test['features']  # taking the colum called feature as a x_test
Y_test= test['label']     # taking the last colum as  label calledy_test
print("test",X_test,Y_test)
print(X_test.shape)
Y_test=np.reshape(Y_test,(360,1)) #reshape the y_test to allow the fitting process 
print(Y_test.shape)

train [[ 0.  0.  4. ... 11.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  4. 16. ...  7.  4.  0.]
 ...
 [ 0.  0.  3. ... 14.  7.  0.]
 [ 0.  0.  2. ... 13.  7.  0.]
 [ 0.  0. 10. ... 16. 16. 10.]] [[1. 4. 2. ... 6. 6. 1.]]
(1077, 64)
(1077, 1)
validation [[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  7. ...  0.  0.  0.]
 [ 0.  0.  4. ...  0.  0.  0.]
 ...
 [ 0.  0.  7. ... 11.  1.  0.]
 [ 0.  0.  1. ... 14.  7.  0.]
 [ 0.  0.  0. ...  5.  0.  0.]] [[4. 7. 7. 8. 7. 4. 4. 7. 6. 5. 3. 9. 5. 4. 1. 0. 7. 3. 4. 4. 9. 2. 7. 8.
  7. 6. 1. 0. 8. 0. 1. 7. 5. 3. 2. 9. 8. 1. 2. 1. 8. 4. 6. 4. 6. 8. 2. 5.
  0. 9. 9. 9. 5. 3. 3. 4. 4. 9. 6. 2. 1. 9. 5. 9. 9. 6. 3. 8. 0. 5. 9. 0.
  0. 1. 0. 5. 1. 6. 6. 8. 2. 9. 2. 9. 4. 7. 6. 0. 2. 6. 2. 6. 5. 1. 8. 1.
  4. 7. 2. 0. 6. 8. 6. 5. 4. 5. 8. 2. 5. 7. 4. 8. 6. 7. 5. 0. 1. 3. 9. 9.
  3. 4. 8. 2. 8. 5. 1. 3. 9. 7. 2. 3. 0. 2. 6. 7. 2. 8. 8. 2. 5. 1. 7. 5.
  1. 1. 5. 0. 8. 1. 1. 8. 0. 0. 5. 8. 0. 2. 2. 2. 3. 1. 9. 1. 7. 6. 0. 1.
  6. 3. 1. 5. 8. 1. 4. 9. 9. 3. 3.

# Decision tree model

Decision Tree made output lower than 95% whatever the depth was may be because it is not the right model to work with 
This value of hyperprameters has been chosen because it achieve high accuracy 

In [4]:
from sklearn import tree
classification = tree.DecisionTreeClassifier(max_depth=17,random_state=43)#selecting the decision tree depth (hyperparameter)which help increase the accuracy

In [5]:
classification = classification.fit(X_train,Y_train)

In [6]:
y_predict= classification.predict(X_val)
print("predicted labels is \n",y_predict)
print("truth table\n",Y_val)

predicted labels is 
 [4. 7. 7. 8. 4. 7. 4. 7. 6. 5. 3. 9. 5. 4. 1. 0. 7. 3. 4. 2. 9. 2. 7. 3.
 7. 6. 1. 0. 8. 0. 9. 7. 5. 2. 2. 9. 0. 1. 2. 1. 8. 4. 6. 4. 6. 8. 2. 5.
 0. 3. 8. 9. 5. 3. 3. 8. 4. 9. 6. 2. 1. 9. 5. 9. 9. 6. 3. 8. 4. 5. 0. 0.
 0. 4. 0. 5. 1. 5. 6. 2. 2. 9. 2. 9. 4. 7. 6. 0. 2. 6. 2. 6. 2. 1. 7. 2.
 7. 7. 2. 0. 6. 8. 6. 5. 0. 5. 8. 2. 5. 7. 4. 8. 6. 7. 5. 0. 4. 3. 9. 9.
 3. 4. 8. 2. 8. 5. 6. 3. 9. 7. 2. 3. 4. 2. 6. 7. 2. 4. 8. 2. 7. 2. 7. 5.
 4. 4. 8. 0. 8. 1. 1. 8. 0. 0. 9. 8. 0. 2. 2. 2. 3. 1. 9. 1. 9. 6. 0. 2.
 6. 3. 8. 5. 8. 1. 4. 9. 9. 3. 3. 2. 3. 2. 7. 7. 5. 5. 8. 7. 8. 7. 7. 8.
 1. 6. 4. 8. 6. 9. 2. 0. 3. 3. 8. 0. 2. 7. 4. 4. 3. 7. 4. 2. 4. 0. 0. 6.
 7. 0. 2. 8. 2. 5. 8. 9. 0. 7. 5. 1. 6. 3. 4. 0. 8. 6. 7. 1. 0. 8. 6. 9.
 6. 7. 4. 4. 8. 7. 7. 1. 8. 4. 6. 7. 0. 6. 9. 4. 1. 2. 4. 8. 1. 0. 7. 1.
 8. 6. 5. 1. 7. 4. 0. 5. 1. 3. 6. 8. 0. 4. 8. 4. 5. 0. 8. 9. 3. 7. 8. 0.
 3. 2. 1. 3. 1. 1. 3. 9. 9. 3. 0. 5. 7. 8. 7. 8. 7. 5. 7. 5. 0. 7. 3. 3.
 5. 8. 9. 1. 9. 9. 2. 6. 2. 9

In [7]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_val, y_predict) # calculate the accuracy score 

0.825

In [8]:
y_predict= classification.predict(X_test)
accuracy_score(Y_test, y_predict)

0.8138888888888889

# k-NN model 

the accuracy of the model cannot reach to 95% whatever the number of neighbours is, may be it is not the right model 
The number of n_neighbors referes to hyperprameters because it achieve high accuracy which possible

In [9]:
import math 
math.sqrt(len(Y_test))

18.973665961010276

In [60]:
from sklearn.neighbors import KNeighborsClassifier
classification2 =KNeighborsClassifier(n_neighbors=12,p=2,metric='euclidear') #choosing the number of neighbors and number of class we want

In [61]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_predict) #we must comput the confusion matrix so we can calculate the accuracy 
print(cm)

[[30  0  0  0  0  1  0  0  1  0]
 [ 0 27  2  2  6  0  0  0  1  0]
 [ 0  0 25  0  2  0  2  0  0  0]
 [ 0  2  2 31  0  1  0  1  1  0]
 [ 3  2  0  0 31  0  0  2  1  0]
 [ 0  0  1  1  0 38  2  1  0  1]
 [ 0  0  0  0  3  0 31  0  0  0]
 [ 0  1  0  0  1  1  0 33  0  1]
 [ 0  0  3  3  3  2  2  0 25  1]
 [ 0  3  0  1  0  1  0  2  1 22]]


In [72]:
from sklearn.metrics import f1_score
print(f1_score(Y_test,y_predict,average='macro')) #knowing the accuracy of the model

0.8144390335814583


In [73]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,y_predict)) 

0.8138888888888889


Logistic Regression

using this model made the accuracy reach to 96% which is more than required 
May be it is the best model as it achieved the highest accuracy 

In [74]:
from sklearn import preprocessing 
from sklearn.linear_model import LogisticRegression
import math
from sklearn import metrics 
from sklearn.metrics import confusion_matrix

In [75]:
logisticRegr=LogisticRegression()
logisticRegr.fit(X_train,Y_train) # fitting between the Y_train and X_train

C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [76]:
print(logisticRegr.predict(X_test[0].reshape(1,-1)))
predictions=logisticRegr.predict(X_test)

[4.]


In [28]:
cm1= metrics.confusion_matrix(Y_test,predictions) 
print(cm1)

[[31  0  1  0  0  0  0  0  0  0]
 [ 0 36  0  0  2  0  0  0  0  0]
 [ 0  1 28  0  0  0  0  0  0  0]
 [ 0  0  0 38  0  0  0  0  0  0]
 [ 0  1  0  0 38  0  0  0  0  0]
 [ 0  0  0  0  0 42  1  1  0  0]
 [ 0  1  0  0  0  0 32  0  1  0]
 [ 0  0  0  0  0  0  0 37  0  0]
 [ 1  1  1  0  0  0  0  0 36  0]
 [ 0  0  0  0  0  1  0  0  0 29]]


In [29]:
score=logisticRegr.score(X_test,Y_test) #calculating the score to know the accuracy of the model
print(score)

0.9638888888888889
