In [1]:
import numpy as np
import pandas as pd
import pickle
with open ('dataset.pkl','rb')as f:
 data = pickle.load(f) # taking the data input using pickle.load fn to read it
print (data)
data.shape #the shape of the data have to be known so we can divid it to 3 parts

          age       sex  bmi body mass index  average blood pressure  \
0    0.038076  0.050680             0.061696                0.021872   
1   -0.001882 -0.044642            -0.051474               -0.026328   
2    0.085299  0.050680             0.044451               -0.005671   
3   -0.089063 -0.044642            -0.011595               -0.036656   
4    0.005383 -0.044642            -0.036385                0.021872   
..        ...       ...                  ...                     ...   
437  0.041708  0.050680             0.019662                0.059744   
438 -0.005515  0.050680            -0.015906               -0.067642   
439  0.041708  0.050680            -0.015906                0.017282   
440 -0.045472 -0.044642             0.039062                0.001215   
441 -0.045472 -0.044642            -0.073030               -0.081414   

     total serum cholesterol  low-density lipoproteins  \
0                  -0.044223                 -0.034821   
1                  

(442, 11)

In this code the colum called blood sugar level has been taken and mapped from regression type to classification type according to a condition set (maybe the condision is not right but what is importnt is the idea)

In [2]:
NL1=[] #creating a list to take the new labels in it  
for row in data['blood sugar level']:
    if row <=.034:  # condition may not true (as a medical information)
        NL1.append(0)
    else:
        NL1.append(1)
print (len(NL1)) 
NL1=np.array(NL1) #converting the NL1 from list to array
NL1=NL1.reshape(442,1) # reshaping the data in this shape to make fitting process on it 


442


In [3]:
from sklearn.model_selection import train_test_split
NL1_train,NL1_test=train_test_split(NL1,test_size=0.2,random_state=43) #seprating the data to validation part with a percentage .2 from the data
print ("first section",NL1_train.shape,NL1_test.shape)
NL1_train,NL1_val=train_test_split(NL1,test_size=0.2,random_state=43)#seprating the data to validation part with a percentage .2 from the data
print ("second section",NL1_train.shape,NL1_val.shape)

first section (353, 1) (89, 1)
second section (353, 1) (89, 1)


In [4]:
NL1_train=NL1_train[:]   # separating the last colum to use it as train , validation ,and test data according to the percentages in the previous code
print("train",NL1_train.shape)
NL1_val=NL1_val[:]
print("validation",NL1_val.shape)
NL1_test=NL1_test[:]
print("test",NL1_test.shape)

train (353, 1)
validation (89, 1)
test (89, 1)


In [5]:
NL2=[] #creating a list to take the new labels in it 
for row in data['disease_progression']:
    if row <=134:   # condition may not true (as a medical information)
        NL2.append(0)
    else:
        NL2.append(1)
print (NL2) 
NL2=np.array(NL2) #converting the NL1 from list to array
NL2=NL2.reshape(442,1) # reshaping the data in this shape to make fitting process on it 

[1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 

In [6]:
from sklearn.model_selection import train_test_split
NL2_train,NL2_test=train_test_split(NL2,test_size=0.2,random_state=43) #seprating the data to validation part with a percentage .2 from the data
print ("first section",NL2_train.shape,NL2_test.shape)
NL2_train,NL2_val=train_test_split(NL1,test_size=0.2,random_state=43)#seprating the data to validation part with a percentage .2 from the data
print ("second section",NL2_train.shape,NL2_val.shape)

first section (353, 1) (89, 1)
second section (353, 1) (89, 1)


In [7]:
NL2_train=NL2_train[:]   # separating the last colum to use it as train , validation ,and test data according to the percentages in the previous code
print("train",NL2_train.shape)
NL2_val=NL2_val[:]
print("validation",NL1_val.shape)
NL2_test=NL2_test[:]
print("test",NL2_test.shape)

train (353, 1)
validation (89, 1)
test (89, 1)


Decisio Tree 
In this model a comparison between the NL1 and NL2 is made on them as we are treating with data and label 

In [8]:
from sklearn import tree
classfd= tree.DecisionTreeClassifier(max_depth=1,random_state=43) #choosing the depth of the tree to know the number of conditions
classfd=classfd.fit(NL1_train,NL2_train) # fitting the train data with each other

In [9]:
y_pred=classfd.predict(NL1_val) #assigning NL1_val value of validation to y_pred
print("predicted model\n",y_pred)
print(NL1_val)

predicted model
 [0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 1 1 0 1 0]
[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]]


In [10]:
print("disease_progression\n",NL2_val)

disease_progression
 [[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]]


In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(NL2_val,y_pred) 

1.0

In [12]:
y_pred=classfd.predict(NL1_test) # assigning ypred to NL1_test 
accuracy_score(NL2_test,y_pred)

0.6853932584269663

#KNN Model 
In this model a comparison between the NL1 and NL2 is made on them as we are treating with data and label 

In [13]:
import math
math.sqrt(len(NL1_test)) #this number helps us to know the number of neighbours

9.433981132056603

In [14]:
from sklearn.neighbors import KNeighborsClassifier
classfd1= KNeighborsClassifier(n_neighbors=7,p=2,metric="euclidear") 

In [15]:
y_pred=classfd.predict(NL1_val) #assigning NL1_val value of validation to y_pred
print("predicted model\n",y_pred)
print(NL1_val)

predicted model
 [0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 1 1 0 1 0]
[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]]


In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(NL2_test,y_pred)  #confusion the matrix of NL2_test with y_predict
print (cm) 

[[41  3]
 [25 20]]


In [17]:
from sklearn.metrics import f1_score
print(f1_score(NL2_test,y_pred,pos_label="positiv",average="micro")) #calculating the score of accuracy of this model

0.6853932584269663


C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positiv') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [18]:
from sklearn.metrics import accuracy_score
print(accuracy_score(NL2_test,y_pred))

0.6853932584269663


Linear Regression 
In this model a comparison between the NL1 and NL2 is made on them as we are treating with data and label 

In [19]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
regression_model = LinearRegression()
regression_model.fit(NL1_train, NL2_train) # Fit the data(train the model)
y_predicted = regression_model.predict(NL1_test) #assigning NL1_test value of validation to y_predicted
mse=mean_squared_error( NL2_test,y_predicted) # model evaluation
rmse = np.sqrt(mean_squared_error(NL2_test, y_predicted))
r2 = r2_score(NL2_test, y_predicted)  #calculating the score of accuracy of this model
print('Slope:' ,regression_model.coef_)
print('Intercept:', regression_model.intercept_)
print('MSE:',mse)
print('Root mean squared error: ', rmse)
print('R2 score: ', r2)

Slope: [[1.]]
Intercept: [3.33066907e-16]
MSE: 0.3146067415730335
Root mean squared error:  0.5608981561505025
R2 score:  -0.2585858585858576
