In [1]:
import numpy as np
import pandas as pd
import pickle
with open ('dataset.pkl','rb')as f:
 data = pickle.load(f) # taking the data input using pickle.load fn to read it
print (data)
data.shape #the shape of the data have to be known so we can divid it to 3 parts

          age       sex  bmi body mass index  average blood pressure  \
0    0.038076  0.050680             0.061696                0.021872   
1   -0.001882 -0.044642            -0.051474               -0.026328   
2    0.085299  0.050680             0.044451               -0.005671   
3   -0.089063 -0.044642            -0.011595               -0.036656   
4    0.005383 -0.044642            -0.036385                0.021872   
..        ...       ...                  ...                     ...   
437  0.041708  0.050680             0.019662                0.059744   
438 -0.005515  0.050680            -0.015906               -0.067642   
439  0.041708  0.050680            -0.015906                0.017282   
440 -0.045472 -0.044642             0.039062                0.001215   
441 -0.045472 -0.044642            -0.073030               -0.081414   

     total serum cholesterol  low-density lipoproteins  \
0                  -0.044223                 -0.034821   
1                  

(442, 11)

In [2]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(data,test_size=0.2,random_state=43) #seprating the data to validation part with a percentage .2 from the data
print ("first section",train.shape,test.shape)
train,val=train_test_split(data,test_size=0.2,random_state=43)#seprating the data to validation part with a percentage .2 from the data
print ("second section",train.shape,val.shape)

first section (353, 11) (89, 11)
second section (353, 11) (89, 11)


In [3]:
x_train=train.iloc[:,0:10]  # separating the last colum to use it as train , validation ,and test data according to the percentages in the previous code 
y_train=train.iloc[:,10:] 
print("train",x_train.shape,y_train.shape)
x_val=val.iloc[:,0:10]
y_val=val.iloc[:,10:]
print("validation",x_val.shape,y_val.shape)
x_test=test.iloc[:,0:10]
y_test=test.iloc[:,10:]
print("test",x_test.shape,y_test.shape)

train (353, 10) (353, 1)
validation (89, 10) (89, 1)
test (89, 10) (89, 1)


Decision Tree Model
we can notic that whatever the depth of the decision tree model is there is no accuracy because the label is in the type of regression not a classification which use another way to calculate the accuracy of the model 

In [4]:
from sklearn import tree
classfd= tree.DecisionTreeClassifier(max_depth=1,random_state=43) #choosing the depth of the tree to know the number of conditions
classfd=classfd.fit(x_train,y_train) # fitting the train data with each other

In [5]:
y_pred=classfd.predict(x_val) #assigning x_vathe value of validation to y_pred
print("predicted model\n",y_pred)
print(x_val)

predicted model
 [200. 200. 220. 220. 220. 200. 200. 220. 200. 220. 200. 220. 200. 200.
 200. 220. 200. 220. 220. 220. 220. 200. 200. 220. 200. 200. 220. 200.
 200. 220. 220. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
 200. 200. 220. 200. 200. 220. 200. 200. 220. 200. 220. 200. 200. 200.
 200. 200. 200. 220. 220. 200. 200. 200. 200. 220. 200. 200. 200. 200.
 200. 200. 200. 200. 200. 200. 200. 220. 200. 220. 200. 200. 220. 220.
 200. 220. 200. 200. 200.]
          age       sex  bmi body mass index  average blood pressure  \
64   0.067136  0.050680            -0.025607               -0.040099   
196 -0.023677 -0.044642            -0.046085               -0.033214   
142  0.041708  0.050680             0.012117                0.039087   
390  0.009016  0.050680             0.069241                0.059744   
353 -0.052738 -0.044642            -0.055785               -0.036656   
..        ...       ...                  ...                     ...   
402  0.110727  0.050680   

In [6]:
print("disease_progression\n",y_val)

disease_progression
      disease_progression
64                  71.0
196                 72.0
142                235.0
390                277.0
353                109.0
..                   ...
402                168.0
319                191.0
3                  206.0
364                262.0
50                 155.0

[89 rows x 1 columns]


In [7]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val,y_pred) # calculating the accuracy score between the validation value of y and x 

0.011235955056179775

In [8]:
y_pred=classfd.predict(x_test) # assigning ypred to x_test 
accuracy_score(y_test,y_pred) #calculating the accuracy score beyween the test value of x and y to test the accuracy of model

0.011235955056179775

 Another Way to read this data
the result is negative because the model is not the best one

In [9]:
import sklearn.metrics as sm
print("R2 score =",sm.r2_score(y_test, y_pred)) # using r2 to calculate the accuracy of the model as this data is in type regression the value is nigative as the model is not the best one

R2 score = -0.39506972671100815


In [10]:
from sklearn.metrics import explained_variance_score
explained_variance_score(y_test, y_pred) 

0.0932316674024295

In [11]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

8706.056179775282

#KNN Model
increasing the number of neighbors did not affect on the accuracy as it still equal zero because the label is in the type of regression not a classification which use another way to calculate the accuracy of the model 

In [12]:
import math
math.sqrt(len(y_test)) #this number helps us to know the number of neighbours

9.433981132056603

In [13]:
from sklearn.neighbors import KNeighborsClassifier
classfd1= KNeighborsClassifier(n_neighbors=10,p=2,metric="euclidear") # appling the KNN model

In [14]:
y_pred=classfd.predict(x_val) #assigning x_vathe value of validation to y_pred
print("predicted model\n",y_pred)
print(x_val)

predicted model
 [200. 200. 220. 220. 220. 200. 200. 220. 200. 220. 200. 220. 200. 200.
 200. 220. 200. 220. 220. 220. 220. 200. 200. 220. 200. 200. 220. 200.
 200. 220. 220. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
 200. 200. 220. 200. 200. 220. 200. 200. 220. 200. 220. 200. 200. 200.
 200. 200. 200. 220. 220. 200. 200. 200. 200. 220. 200. 200. 200. 200.
 200. 200. 200. 200. 200. 200. 200. 220. 200. 220. 200. 200. 220. 220.
 200. 220. 200. 200. 200.]
          age       sex  bmi body mass index  average blood pressure  \
64   0.067136  0.050680            -0.025607               -0.040099   
196 -0.023677 -0.044642            -0.046085               -0.033214   
142  0.041708  0.050680             0.012117                0.039087   
390  0.009016  0.050680             0.069241                0.059744   
353 -0.052738 -0.044642            -0.055785               -0.036656   
..        ...       ...                  ...                     ...   
402  0.110727  0.050680   

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)  #confusion the matrix of y_test with y_predict
print (cm) 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
from sklearn.metrics import f1_score
print(f1_score(y_test,y_pred,pos_label="positiv",average="micro")) #calculating the accuracy score of the model between y_test and y_pred which points to x_val

0.011235955056179775


C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1386: UserWarning: Note that pos_label (set to 'positiv') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [17]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))  #calculating the accuracy score of the model between y_test and y_pred which points to x_test

0.011235955056179775


Another Way to read this data

In [18]:
import sklearn.metrics as sm
print("R2 score =",sm.r2_score(y_test, y_pred))

R2 score = -0.39506972671100815


Linear Regression 

In [19]:
from sklearn import linear_model
reg= linear_model.LinearRegression()
reg.fit(x_train,y_train)
print("Score= {}".format(reg.score(x_test,y_test))) #calculating the accuracy score in linear regression model

Score= 0.5419894894683135


Another Way to read this data

In [20]:
import sklearn.metrics as sm
print("R2 score =", sm.r2_score(y_test, y_pred))

R2 score = -0.39506972671100815
